import { GIFProps } from '@/@types/models';

export const mockGIFListApi: GIFProps[] = [
  {
    id: 'gif123',
    slug: 'test-gif',
    embed_url: 'https://example.com/embed',
    source: 'https://example.com/source',
    images: {
      original: {
        url: 'https://example.com/image.gif',
        height: '',
        width: '',
        size: '',
        mp4_size: '',
        mp4: '',
        webp_size: '',
        webp: '',
        frames: '',
        hash: '',
      },
      downsized: {
        height: '',
        width: '',
        size: '',
        url: '',
      },
    },
    title: 'Test GIF',
    url: 'https://example.com',
    rating: 'PG',
  },
  {
    id: 'gif456',
    slug: 'test-gif-2',
    embed_url: 'https://example.com/embed',
    source: 'https://example.com/source',
    images: {
      original: {
        url: 'https://example.com/image.gif',
        height: '',
        width: '',
        size: '',
        mp4_size: '',
        mp4: '',
        webp_size: '',
        webp: '',
        frames: '',
        hash: '',
      },
      downsized: {
        height: '',
        width: '',
        size: '',
        url: '',
      },
    },
    title: 'Test GIF 2',
    url: 'https://example.com',
    rating: 'G',
  },
  {
    id: 'gif789',
    slug: 'test-gif-3',
    embed_url: 'https://example.com/embed',
    source: 'https://example.com/source',
    images: {
      original: {
        url: 'https://example.com/image.gif',
        height: '',
        width: '',
        size: '',
        mp4_size: '',
        mp4: '',
        webp_size: '',
        webp: '',
        frames: '',
        hash: '',
      },
      downsized: {
        height: '',
        width: '',
        size: '',
        url: '',
      },
    },
    title: 'Test GIF 3',
    url: 'https://example.com',
    rating: 'R',
  },
];
